/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as taskSol from "./Task.sol";
export type { taskSol };
export type { Registry } from "./Registry";
export * as factories from "./factories";
export { Registry__factory } from "./factories/Registry__factory";
export type { Agent } from "./Task.sol/Agent";
export { Agent__factory } from "./factories/Task.sol/Agent__factory";
export type { Task } from "./Task.sol/Task";
export { Task__factory } from "./factories/Task.sol/Task__factory";
