/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { Agent, AgentInterface } from "../../Task.sol/Agent";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "_message",
        type: "string",
      },
    ],
    name: "sendMessage",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class Agent__factory {
  static readonly abi = _abi;
  static createInterface(): AgentInterface {
    return new Interface(_abi) as AgentInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Agent {
    return new Contract(address, _abi, runner) as unknown as Agent;
  }
}
